lsst-epo/rubin-obs-client

.env.local.sample
Dockerfile

Only affects node version used by docker in cloud envs

Node version bump

---

lib/utils.js

[B] Fix mailto links

---

components/content-blocks/Link/index.js

[B] Fix LinkContentBlock url

---

components/page/FilterBar/index.js
lib/localeStrings/en.json

Resolves #62 
The issue mentions that this is also a problem is in the header search, but that search already has a label 👍

[B] Add label to filter search

---

lib/api/pages.js

[B] Fix breadcrumbs localization issue

---

components/content-blocks/GridBlock/NewsGrid.js
components/dynamic/JobList/index.js
components/dynamic/NewsList/index.js
components/templates/HomePage/index.js
components/templates/StaffPage/index.js
lib/localeStrings/en.json
lib/localeStrings/es.json
lib/utils.js

[B] Fix job and post type i18n

---

components/dynamic/EventList/index.js
components/templates/EventPage/index.js
lib/localeStrings/en.json
lib/localeStrings/es.json

[B] Use backend translations for event types

---

components/global/Header/LanguageSelect/index.js
components/global/Header/LanguageSelect/styles.js
components/global/Header/_navigation.scss
components/global/Header/index.js
lib/localeStrings/en.json
lib/localeStrings/es.json
theme/styles/globalStyles.js

[B] Fix hidden language toggle

---

components/templates/Page/index.js

[B] Fix missing upcoming and past buttons on events page

---

components/templates/Page/index.js

[F] Allow staff profiles to be sortable, filterable, searchable

---

components/dynamic/EventList/index.js
components/dynamic/EventList/styles.js
components/templates/EventPage/index.js
lib/api/fragments/event.js
theme/styles/globalStyles.js

[F] Add end date to event detail page

---

components/atomic/Button/index.js
components/atomic/Button/styles.js
components/atomic/Buttonish/index.js
components/atomic/Carousel/Carousel/styles.js
components/content-blocks/Callout/styles.js
components/modal/ForgotPasswordModal/index.js
components/modal/RegisterModal/JoinForm/index.js
components/modal/RegisterModal/RegisterForm/index.js
theme/styles/globalStyles.js
theme/styles/mixins/appearance.js

@dananjohnson I made a PR to call out some major updates to the button styling. Take a quick peep and let me know if something seems off 👀 
- Consolidated the button styles into styles/mixins/appearance.js
- Updated "secondary" style to be red, added "teacher" style (orange)
- Updated hover, focus states

[F] Update button color, hover, and focus states

---

components/page/SubHero/index.js
components/templates/Page/index.js
lib/api/fragments/page.js

[F] Add sub heros to pages

---

components/atomic/index.js
components/auth/AuthorizePage/index.js
components/dynamic/GlossaryList/index.js
components/templates/GlossaryPage/index.js
components/templates/Page/index.js
hooks/useAuthentication.js
lib/api/auth.js
lib/api/entries.js
lib/api/entry.js
lib/api/fragments/educator-page.js
lib/api/global.js
lib/api/pages.js
lib/localeStrings/en.json
pages/[[...uriSegments]].js
theme/styles/mixins/appearance.js

- Filters educator pages from global navigation
- Adds page auth check (all educator pages are restricted)
- _Does not_ prevent users from clicking on a restricted link (will be investigated in a follow up PR)

[F] Add educator pages and page auth check

---

components/content-blocks/ComplexTable/index.js
components/content-blocks/ComplexTable/styles.js
components/content-blocks/TableGroup/index.js
components/content-blocks/TableGroup/styles.js
components/content-blocks/index.js
components/factories/ContentBlockFactory.js
components/layout/Container/index.js
components/layout/Container/styles.js
lib/api/fragments/content-blocks.js
lib/api/fragments/educator-page.js
lib/api/fragments/event.js
lib/api/fragments/homepage.js
lib/api/fragments/page.js
lib/api/fragments/student-page.js

Requires @kylepratuch 's rubin-obs-api branch `kp-super-table` to be merged into develop.

[F] Build and style Complex Table and Table Group content blocks

---

pages/_app.js

Pageproofer will allow internal stakeholders to provide feedback in a "sticky note" fashion

[C] Add pageproofer snippet

---

lib/api/entries.js

https://nextjs.org/docs/messages/gsp-redirect-during-prerender

[B] Exclude redirect pages from SSG

---

components/atomic/Tile/patterns/InvestigationTile/index.js
components/atomic/Tile/patterns/InvestigationTile/styles.js
components/atomic/index.js
components/content-blocks/GridBlock/InvestigationGrid.js
components/content-blocks/GridBlock/index.js
components/factories/ContentBlockFactory.js
lib/api/fragments/content-blocks.js
lib/api/fragments/educator-page.js
lib/api/fragments/event.js
lib/api/fragments/homepage.js
lib/api/fragments/investigation-landing-page.js
lib/api/fragments/page.js
lib/api/fragments/student-page.js
lib/localeStrings/en.json
lib/localeStrings/es.json

[F] Build investigations grid

---

pages/_app.js

[G] Add analytics snippet

---

components/content-blocks/GridBlock/MainGrid.js
lib/api/fragments/content-blocks.js

- Adds investigations to related content
- Uses landingPage uri for uri
- No description field on investigations yet, will need to be added to the backend/API first

[F] Add investigations to related content

---

components/page/Breadcrumbs/index.js

Don't render Breadcrumbs if length <= 1

resolve #65

---

pages/[[...uriSegments]].js

Bug fix checking for null in static build function

---

components/atomic/Tile/index.js

[B] Hide "Read More" buttons from screen readers

---

components/templates/EventPage/index.js
components/templates/NewsPage/index.js

[B] Update unnecessary h4 tags to divs in Event Page

---

.github/workflows/dev-pull-request.yaml
.github/workflows/dev-push.yaml
.github/workflows/master-pr.yaml
.github/workflows/master-push.yaml
.github/workflows/prod-push.yaml
Dockerfile
pages/_app.js

- Add levelaccess env var
- Prune env var inclusion to only applicable environments
- Add check to only include script tag in presence of required env var

Add LevelAccess snippet

---

components/content-blocks/Embed/index.js
components/content-blocks/index.js
components/factories/ContentBlockFactory.js
lib/api/fragments/content-blocks.js
lib/api/fragments/educator-page.js
lib/api/fragments/event.js
lib/api/fragments/homepage.js
lib/api/fragments/investigation-landing-page.js
lib/api/fragments/page.js
lib/api/fragments/student-page.js

Basic iframe embed Content Block with option for full bleed of body container width container

[EPO-6579] Basic iframe embed ContentBlock

---

components/form/AuthModalPasswordField/index.js
components/form/index.js
components/layout/InvestigationHero/index.js
components/modal/RegisterModal/RegisterForm/index.js
components/modal/SetPasswordModal/index.js

- Softened password input validation
- Allow more special characters in validation

[EPO-6674] Improved password input field validation

---

components/global/Header/LanguageSelect/styles.js
components/global/Header/_navigation.scss

[B] Set max-width for mobile nav & subnav

---

components/auth/AuthorizePage/index.js
components/auth/AuthorizePage/styles.js
components/modal/RegisterModal/JoinForm/index.js
components/modal/SignInModal/index.js
hooks/useAuthentication.js

Only option for Educator type users to login and sign up. Affected at state level and commenting out related UI

Removes Student User flows

---

next.config.js

Update with these config changes: https://nextjs.org/docs/advanced-features/compiler#styled-components to resolve error message

[C] update next.config for styled-components

---

lib/api/fragments/global.js

Image was querying at 600px getting a blurry result

[C] increase size of supporter logo in query

---

.eslintrc.js
.gitignore
.storybook/decorators.jsx
.storybook/i18next.js
.storybook/main.js
.storybook/preview.js
package.json
yarn.lock

For JIRA: "EPO-7873 #IN-REVIEW #comment add Storybook"

[F] add Storybook

---

.github/workflows/dev-pull-request.yaml
.github/workflows/dev-push.yaml
.github/workflows/master-pr.yaml
.github/workflows/master-push.yaml
pages/[[...uriSegments]].js

Added additional logging for node.js server

---

components/layout/WidgetGrid/WidgetGrid.stories.jsx
components/layout/WidgetGrid/index.js
components/layout/WidgetGrid/styles.js

For JIRA: "EPO-7926 #IN-REVIEW #comment add WidgetGrid"

[F] WidgetGrid

---

.storybook/i18next.js
components/layout/WidgetGrid/WidgetGrid.stories.jsx
components/layout/WidgetPreview/WidgetPreview.stories.jsx
components/layout/WidgetPreview/index.js
components/layout/WidgetPreview/styles.js
lib/localeStrings/en.json

Component to display previews of the widget sections for Summit Status Dashboard

[F] WidgetPreview

---

components/atomic/Button/IconButton/IconButton.stories.jsx
components/atomic/Button/IconButton/index.js
components/atomic/Button/IconButton/styles.js
components/layout/WidgetPreview/index.js
components/layout/WidgetPreview/styles.js
components/layout/WidgetSection/WidgetSection.stories.jsx
components/layout/WidgetSection/index.js
components/layout/WidgetSection/styles.js
package.json
yarn.lock

For JIRA: "EPO-7933 #IN-REVIEw #comment add WidgetSection"

[F] WidgetSection

---

lib/api/fragments/content-blocks.js
lib/api/fragments/educator-page.js
lib/api/fragments/event.js
lib/api/fragments/investigation-landing-page.js
lib/api/fragments/news-post.js
lib/api/fragments/page.js
lib/api/fragments/staff-profile.js
lib/api/fragments/student-page.js

- Includes all smaller format image componets like tiles and thumbnails, and some larger format image components like featured images and news assets

[EPO-8103] Higher resolution images

---

components/content-blocks/SummitStatus/index.js
components/content-blocks/index.js
components/factories/ContentBlockFactory.js
components/layout/UnitLocalization/index.js
components/layout/UnitLocalization/styles.js
components/shapes/svg.js
components/svg/UniqueIconComposer.jsx
components/svg/unique/Gear.js
components/svg/unique/index.js
lib/api/fragments/content-blocks.js
lib/localeStrings/en.json
theme/styles/globalStyles.js

For JIRA: "EPO-8027 #IN-REVIEW #comment set up content block"

[F] Summit Status content block

---

components/content-blocks/SummitStatus/index.js
components/layout/WidgetPreview/styles.js
components/widgets/TemperatureCurrent/index.js
components/widgets/TemperatureHIstoric/index.js
components/widgets/TemperatureHIstoric/styles.js
helpers/index.js
lib/localeStrings/en.json

Table that displays the highs and lows for a given day of the week. Component accepts an array of temperatures attached to a weekday index corresponding to JavaScript's `date.getDay()` return

[F] TemperatureHistoric table widget

---

components/atomic/WidgetBackground/index.js
components/atomic/WidgetBackground/styles.js
components/content-blocks/Callout/CalloutEntry/index.js
components/content-blocks/Callout/CalloutEntry/styles.js
components/content-blocks/SummitStatus/index.js
components/layout/WidgetPreview/styles.js
components/widgets/PrecipitationCurrent/index.js
components/widgets/PrecipitationCurrent/styles.js
components/widgets/TemperatureCurrent/index.js
components/widgets/TemperatureCurrent/styles.js
components/widgets/TemperatureHIstoric/index.js
components/widgets/TemperatureHIstoric/styles.js
helpers/index.js
lib/api/fragments/content-blocks.js
lib/api/investigation.js
lib/localeStrings/en.json

add PrecipitationCurrent widget and extract the background panel all widgets using into an atomic component

[F] add PrecipitationCurrent

---

components/atomic/WidgetBackground/index.js
components/atomic/WidgetBackground/styles.js
components/content-blocks/SummitStatus/index.js
components/layout/UnitLocalization/index.js
components/layout/WidgetGrid/styles.js
components/layout/WidgetPreview/styles.js
components/shapes/units.js
components/widgets/PrecipitationCurrent/index.js
components/widgets/PrecipitationCurrent/styles.js
components/widgets/TemperatureCurrent/index.js
components/widgets/TemperatureCurrent/styles.js
components/widgets/TemperatureHIstoric/index.js
components/widgets/TemperatureHIstoric/styles.js
helpers/index.js
lib/localeStrings/en.json

Added TemperatureCurrent widget, shapes for the units (reverted back to "fahrenheit" and "celsius" since this is what JavaScript's `toLocaleString` expects as valid units)

[F] add TemperatureCurrent widget

---

components/charts/ChartFigure/styles.js
components/dynamic/SummitData/Astroweather/Forecast/index.js
components/dynamic/SummitData/Astroweather/index.js
components/modal/SummitStatusModal/styles.js
components/widgets/CurrentData/patterns/MoonRise/index.js
components/widgets/CurrentData/patterns/MoonRise/styles.js
helpers/formatters.js
lib/localeStrings/en.json
package.json
yarn.lock

For JIRA: "EPO-8245 #IN-REVIEW #comment Moonrise widget"
Moonrise/set widget that shows the time of the next moonrise and moonset at the Rubin Observatory.

[F] Moonrise widget

---

.eslintrc.js
components/atomic/RadialMeter/index.js
components/atomic/RadialMeter/styles.js
components/content-blocks/SummitStatus/index.js
components/dynamic/SummitData/Observation/Instruments/index.js
components/dynamic/SummitData/Observation/Instruments/styles.js
components/dynamic/SummitData/Observation/index.js
components/dynamic/SummitData/Observation/styles.js
components/widgets/CurrentData/patterns/Azimuth/index.js
components/widgets/CurrentData/patterns/Azimuth/styles.js
components/widgets/CurrentData/patterns/ShutterSpeed/index.js
components/widgets/CurrentData/patterns/ShutterSpeed/styles.js
components/widgets/CurrentData/patterns/SlewSpeed/index.js
components/widgets/CurrentData/patterns/SlewSpeed/styles.js
components/widgets/CurrentData/patterns/Zenith/index.js
components/widgets/CurrentData/patterns/Zenith/styles.js
helpers/index.js
lib/localeStrings/en.json
lib/localeStrings/es.json

Zenith and Azimuth widgets along with their implementation in a new "Observation" section of the page.

[F] Zenith and Azimuth widgets

---

.github/workflows/build-and-push.yaml

Fixes the environment parsing logic so it correctly selects int
Also commented out the PR trigger events for now while PR preview functionality is under development.

Workflow fix for Int deployments

---

components/atomic/Tile/index.js
components/atomic/Tile/patterns/InvestigationTile/index.js
components/atomic/Tile/patterns/SlideTile/index.js
package.json
pages/_app.js

Replace react-uid with built-in `useId()` hook for better SSR stability 
Resolves #437

[C] replace react-uid

---

pages/api/revalidate.js

Added debug line to `revalidate.js`

Added debug line to `revalidate.js`

---

package.json
yarn.lock

[D] update Next.js

---

components/content-blocks/KeyNumbersGridBlock/index.js
components/content-blocks/KeyNumbersGridBlock/styles.js

[C] key numbers markup & styling

---

middleware.js

Stringified middleware logging + ignore localhost

Stringified middleware logging + ignore localhost

---

middleware.js

Omitting localhost from middleware logging

Omitting localhost from middleware logging

---

components/content-blocks/Callout/CalloutEntry/index.js
components/content-blocks/GridBlock/index.js
components/layout/NavButtons/index.js
components/layout/Tabs/index.js
components/page/FilterBar/index.js
next.config.js
package.json
yarn.lock

Update `@rubin-epo/epo-react-lib` to latest to be on-par with other applications.

[D] libraries update

---

lib/purgeStaticFiles.js
pages/[[...uriSegments]].js

[C] purge static files after page 404 during build

---

components/global/Header/LanguageSelect/index.js

Instead of getting the locale from the URI string, which can be finicky since our middleware is re-writing it to remove the `[locale]` segment when set to English, use the resolved locale from `i18next`. This isn't an ideal fix since i18next's state is derived from Next.js, but since Next's own router can get confused by rewrites it is more reliable.

fix: get locale from i18next instead of URI

---

next-env.d.ts
package.json
tsconfig.json
yarn.lock

build: install TypeScript

---

lib/api/entry.js
lib/api/globals/index.ts

Reverts lsst-epo/rubin-obs-client#545

Revert "fix: cache global and page queries"

---

app/robots.ts

feat: robots.txt generation

---

components/atomic/Tile/index.js
components/atomic/Tile/styles.js

fix: remove padding from top of tile images

---

components/templates/NewsPage/index.tsx
lib/api/noirlab/index.ts
openapi-ts.config.ts
package.json
yarn.lock

allow limited iframe content in press releases

refactor: allow iframe in press release content

---

components/molecules/Logo/styles.module.css
components/templates/NewsPage/index.tsx
lib/api/noirlab/index.ts
openapi-ts.config.ts

Make Noirlab endpoint env var public

fix: make noirlab endpoint public

---

app/[locale]/gallery/[gallery]/layout.tsx

fix: preserve urisegments fallback

---

package.json

Changing the port back to `8080` from `3000`

Changing the port back to `8080` from `3000`

---

.github/workflows/build-and-push.yaml

Updated branch name in workflow

Updated branch name in workflow

---

.github/workflows/build-and-push.yaml

Update GitHub Action workflow to trigger on main branch instead of master

update workflow branch from master to main

---

components/organisms/gallery/GalleryList/index.tsx
components/organisms/gallery/GalleryList/styles.module.css
components/organisms/gallery/PreviewGrid/index.tsx
components/templates/GalleryPage/index.tsx
components/templates/GalleryPage/styles.module.css
gql/gql.ts
lib/api/galleries/index.ts

feat: show all galleries on page

---

lib/api/client/query.ts
package.json
yarn.lock

fix: add graphQL retry

---

package.json
yarn.lock

fix: resolve vulnerability incident

---

components/atomic/Button/Hamburger/index.tsx
components/atomic/Tile/index.js
components/atomic/Tile/patterns/SlideTile/index.js
components/content-blocks/Callout/CalloutMain.js
components/global/ContactInfo/index.js
components/global/Footer/ContactForm.js
components/molecules/Aside/Image/index.tsx
components/molecules/Aside/Section/index.tsx
components/molecules/ClearFiltersButton/index.tsx
components/molecules/FilterDropdownList/index.tsx
components/molecules/GalleryImage/index.tsx
components/molecules/HeaderLevel/index.tsx
components/molecules/LinkedImage/index.tsx
components/molecules/Logo/index.tsx
components/molecules/MetadataList/index.tsx
components/molecules/Search/index.tsx
components/molecules/SearchBar/index.tsx
components/molecules/TagList/index.tsx
components/organisms/Filters/index.tsx
components/organisms/Header/NavItem.js
components/organisms/Header/NavItemWithChildren.js
components/organisms/Header/Subnavigation.js
components/organisms/Header/navigation/Horizontal/index.tsx
components/organisms/Header/navigation/Vertical/index.tsx
components/organisms/gallery/GalleryList/index.tsx
components/organisms/gallery/MediaPolicy/index.tsx
components/templates/GalleryPage/index.tsx
package.json
yarn.lock

perf: replace classnames with clsx

---

next.config.js

perf: increase Next image cache TTL to 1 hour

---

components/content-blocks/TableGroup/index.js
components/layout/UnitLocalization/styles.js
components/modal/AuthModal/index.js
components/modal/AuthModal/styles.js
components/modal/SummitStatusModal/styles.js
components/molecules/FilterDropdownList/index.tsx
components/molecules/SharePopup/index.tsx
package.json
yarn.lock

Pre-work for #776 so that main site can use latest libraries, updates headlessui imports to follow 2.x export convention

build: update @headlessui/react

---

components/content-blocks/Callout/CalloutEntry/index.js

fix: pass background as CSS variable for news callout

---

components/content-blocks/Image/index.tsx
components/content-blocks/Image/styles.module.css
components/molecules/GalleryImage/GalleryImage.cy.tsx
components/molecules/GalleryImage/index.tsx
components/organisms/InlineCantoImage/index.tsx
components/organisms/gallery/CantoImage/index.tsx
components/templates/GlossaryPage/index.js
gql/gql.ts
lib/api/fragments/content-blocks.js
lib/api/galleries/schema.ts
services/craft/entries/content-blocks/image.ts
services/craft/fragments/CantoAssetDetailed.gql

feat: canto assets for image blocks

---

components/content-blocks/Skyviewer/index.tsx

chore: add 'allow-forms' to Skyviewer iframe

---

app/api/revalidate/route.ts
lib/api/client/tags.ts
lib/api/galleries/asset.ts
lib/api/galleries/index.ts
services/revalidation/additional.ts
services/revalidation/indexNow.ts

fix: revalidate galleries using slug as tag

---

components/organisms/MediaAside/GalleryAsset/index.tsx

fix: provided locale to assetTitle call

---

app/api/revalidate/route.ts
services/revalidation/additional.ts
services/revalidation/index.ts

test: added debug logging

---

components/organisms/Footer/_footer.scss
components/organisms/Footer/index.js
gql/gql.ts

feat: remove contact form
