components/content-blocks/ShareBlock/index.js, components/content-blocks/Text/index.js, components/layout/Container/index.js, components/layout/Container/styles.js, components/templates/EventPage/index.js, components/templates/NewsPage/index.js, components/templates/Page/index.js, theme/styles/abstracts/_functions.scss, theme/styles/components/_content-rte.scss, theme/styles/utility/_layout.scss
- Adjusts header padding in RTE to style guide
- Adds optional paddingSize prop to Containers
- Adjusts share icon and header padding on news pages, event pages, text content elements, and non-dynamic pages to "medium" (40px)
- Resolves #16 and #18 
Needs a quick visual review by José before merge
=> [F] Adjust header and share padding

.github/workflows/dev-pull-request.yaml, .github/workflows/dev-push.yaml, .github/workflows/master-pr.yaml, .github/workflows/master-push.yaml, .github/workflows/prod-push.yaml
Encoutering [error on build](https://github.com/lsst-epo/rubin-obs-client/runs/5649165156?check_suite_focus=true):
```
Error: On 2022-04-05, the default branch will be renamed from "master" to "main". Your action is currently pinned to "@master". Even though GitHub creates redirects for renamed branches, testing found that this rename breaks existing GitHub Actions workflows that are pinned to the old branch name.
```
Following suggestion:
```
We strongly advise updating your GitHub Action YAML from:
uses: 'google-github-actions/setup-gcloud@master'
to:
uses: 'google-github-actions/setup-gcloud@v0'
```
Seems like it's done the trick.
=> [B] Github workflows have correct main branch refs for gcloud

.github/workflows/dev-pull-request.yaml, .github/workflows/master-pr.yaml, .github/workflows/prod-push.yaml
This changes the prod deployment trigger so that it will only trigger on pushes of tags that start with 'v' (e.g. v1.0.0)
=> Fix prod deployments

lib/api/sibling-nav.js
On pages that have the "sibling nav" enabled, the "next" and "previous" links are disabled if you are on the first or last sibling page (respectively). 
In some cases, Craft CMS considers pages to be siblings even if they do not have the same parent.
Adds filter param to `getSiblings` graphQL query that only includes `prev` or `next` siblings in the response if their parent entry id matches the current page's parent id (i.e. the siblings and the current page all have the same parent).  Additionally, if a page has no parent it is assumed it has no siblings and therefore query is not made and `addSiblings` returns `{}` instead of querying the CMS.
Please test all page types:
- A Page with the Sibling Nav enabled.  For instance the previous button should be grayed out on …
=> Sibling Nav siblings are only siblings is they have the same parent

lib/utils.js, pages/_document.js
For JIRA: "EPO-7309 #IN-REVIEW #comment loosen URL locale checking"
News article previews on the homepage were not showing their localized text. The `entries` graphQL query was always setting `site` to `default` regardless of the locale set on the frontend. Issue was in the `getSiteString()` utility method, for non-array language data a simple `includes()` or typed value comparison was used. The `includes()` search string was `/es/` which will return true for any page prefixed with the `es` locale _except_ for the homepage which does not have a trailing slash.
To fix this, I loosened the search string to `/es` but since this is such a low level function I am concerned it may have unintended impact on other URLs. For example a URL string like `/article/escape-from-new-york` could return as …
=> [C] loosen URL locale checking

pages/[[...uriSegments]].js, pages/api/preview.js, yarn.lock
page entry URIs with es successfully query entry data from provided uri, while using the same dedicated previewUri strategy EN page entries use.  Also mmoved the dedicated previewUri value into an ENV VAR called NEXT_PREVIEW_SLUG
=> ES pages' previews fix

.storybook/main.js, components/charts/Bar/index.js, components/charts/Bar/styles.js, components/charts/BarData/index.js, components/charts/ChartBase/index.js, components/charts/ChartFigure/ChartFigure.stories.js, components/charts/ChartFigure/index.js, components/charts/ChartFigure/styles.js, components/charts/Legend/index.js, components/charts/Legend/styles.js, components/charts/LineData/index.js, components/charts/LineData/styles.js, components/charts/Tooltip/index.js, components/charts/Tooltip/styles.js, components/charts/XAxis/index.js, components/charts/XAxis/styles.js, components/charts/YAxis/index.js, components/charts/YAxis/styles.js, components/charts/index.js, jsconfig.json, lib/utils.js, package.json, yarn.lock
- Added charting tools to support Summit Status Dashboard, no new dependencies pulled in for charting. Dependency change comes from adding Storybook a11y addon.
- The ChartFigure component is the only component with a story and contains two examples: one with bar and line graph data, and the other with bar graph data but overflowing the parent container. The overflow occurs automatically and is based on the specified height of the chart.
- There is no singular "Chart" component where a config and some data are passed resulting in a chart; rather these are components intended to be assembled as needed into containers for charts. They may be mixed, matched, and enhanced with bespoke components as-needed, there is no prescribed "Bar Graph" or "Line Graph".
=> [F] Charting lib

components/content-blocks/SummitStatus/index.js, components/layout/UnitLocalization/index.js, components/layout/UnitLocalization/styles.js, components/shapes/svg.js, components/svg/UniqueIconComposer.jsx, components/svg/unique/Gear.js, components/svg/unique/index.js, lib/localeStrings/en.json
Toolbar for picking local temperature and windspeed units. Controls state of the SummitStatus block which is put into a provider. Default selections are determined by the user's current locale.
Design
Client
=> [F] Unit localization toolbar

components/atomic/Loader/index.js, components/atomic/Loader/styles.js, components/content-blocks/GridBlock/CarouselGrid/index.js, components/content-blocks/GridBlock/MainGrid.js, components/content-blocks/GridBlock/NewsGrid.js, components/dynamic/DataList/index.js, components/dynamic/DataList/styles.js, components/dynamic/EventList/index.js, components/dynamic/EventList/styles.js, components/dynamic/GalleryList/index.js, components/dynamic/GlossaryList/index.js, components/dynamic/JobList/index.js, components/dynamic/JobList/styles.js, components/dynamic/NewsList/index.js, components/dynamic/RelatedList/index.js, components/dynamic/SearchList/index.js, components/dynamic/SlideshowList/index.js, components/dynamic/StaffList/index.js, components/templates/NewsPage/index.js, components/templates/StaffPage/index.js, lib/localeStrings/en.json, lib/localeStrings/es.json, package.json, pages/[[...uriSegments]].js, pages/_document.js, yarn.lock
Loader graphic implemented across "dynamic" `dataList` and `gridBlock` components.  Loader should appear on page load, then be removed after successful data fetch.  Please review on pages with dynamic dataLists:
- /news
- /explore/voices/all-rubin-voices
- /calendar
- /gallery/slideshows
- /education/glossary
- /about/work-with-us/jobs (n.b. this page is currently disabled but there are jobs entries, so can be reviewed on local if page is reenabled)
- /search?search=space&page=1
and also on pages that have dynamic contentBlocks:
- a news post (the "related" section at the bottom)
- an event (the "related" section at the bottom)
- a Rubin Voices page with a "related" block
- a normal page with a "related" block
- homepage (news block at the bottom)
=> [EPO-8165] Loading Spinner implementations

components/atomic/Loader/styles.js, components/content-blocks/SummitStatus/index.js, components/dynamic/SummitData/Weather/Current/index.js, components/dynamic/SummitData/Weather/Daily/index.js, components/dynamic/SummitData/Weather/Hourly/index.js, components/dynamic/SummitData/Weather/index.js, components/layout/UnitLocalization/index.js, components/layout/WidgetSection/index.js, components/layout/WidgetSection/styles.js, components/modal/SummitStatusModal/index.js, components/modal/SummitStatusModal/styles.js, components/widgets/CurrentData/patterns/Windspeed/index.js, components/widgets/HourlyData/patterns/Precipitation/index.js, components/widgets/HourlyData/patterns/Windspeed/index.js, components/widgets/HourlyData/styles.js, contexts/SummitData.js, contexts/WeatherUnit.js, helpers/converters.js, helpers/formatters.js, lib/api/queries/weather.js, lib/localeStrings/en.json
This adds the modal that will contain all "detail" sections on the summit dashboard along with an implementation of the weather widgets.
There is one other major change included here, the weather unit provider has been refactored so that the unit localization selector does not need to have props and callbacks passed up and down through the individual sections and their modals. I have also trimmed down the data queries for the weather data to improve load times.
=> [F] SummitStatus modal + weather widgets setup

contexts/SummitData.js, lib/api/efd.js, pages/api/efd/[type].js
A bit of an add on and resulting refactor.  As of writing this comment, the USDF is down for scheduled maintainence, so a little tricky to 100% know this is all working, but suffice to say the goals of this change were thus:
- move the use of the EFD credentials serverside so they're not exposed to the browser/clever users
And then, while I was in there, [based on some of the examples of this kind of thing I was seeing](https://www.smashingmagazine.com/2021/12/protect-api-key-production-nextjs-api-route/) it seemed like I could also incorporate SWR, and that it would do some/all of the statey promisey stuff for us?  But that's both the part that's hard for me to understand without actually being able to reach the USDF EFD, and also the part I am the least knowledgable in. I very well may …
=> [EPO-8239] EFD secrets are secret

components/dynamic/SummitData/Astroweather/Current/index.js, components/dynamic/SummitData/Astroweather/Forecast/index.js, components/dynamic/SummitData/Astroweather/index.js, components/dynamic/SummitData/Observation/Related/index.js, components/dynamic/SummitData/Weather/Current/index.js, components/dynamic/SummitData/Weather/Daily/index.js, components/dynamic/SummitData/Weather/Hourly/index.js, components/dynamic/SummitData/Weather/index.js, components/widgets/CurrentData/patterns/Daylight/index.js, components/widgets/CurrentData/patterns/MoonRise/index.js, components/widgets/DailyData/patterns/Moonrise/Time/index.js, components/widgets/DailyData/patterns/Moonrise/index.js, contexts/SummitData.js, lib/api/astroweather.js, lib/api/efd.js, lib/suncalc.js, pages/api/astroweather.js
Move all astroweather calcs into a single API that returns lunar phase, lunar times, and sun times via useSWR hook.
Removed redundant code and updated some props
=> [C] move astroweather calcs to endpoint

lib/api/fragments/image.js, lib/utils.js, yarn.lock
Canto's preview URL's are always in JPG format, this breaks GIF formats on smaller screen sizes. Short circuit this behavior by adding filetype to the asset query and using the original URL instead.
=> [C] use original URL for GIF

.github/workflows/build-and-push.yaml
Replaces the environment determination logic with the correct logic that includes "dev" as the default environment
=> More Workflow Fixes

components/content-blocks/Callout/CalloutEntry/index.js, components/content-blocks/Callout/CalloutEntry/styles.js, components/content-blocks/Callout/CalloutMain.js, components/content-blocks/Callout/CalloutTwoTone.js, components/content-blocks/Callout/Wrapper.js, components/content-blocks/Callout/styles.js, components/content-blocks/GridBlock/index.js, components/layout/ChildNavigation/index.js, components/layout/StepNavigation/index.js, components/layout/StepNavigation/styles.js, components/page/Breadcrumbs/styles.js, components/page/Hero/index.js, components/page/Hero/styles.js, components/page/PageContent/index.js, components/page/PageContent/styles.js, components/templates/EventPage/index.js, components/templates/EventPage/styles.js, components/templates/HomePage/index.js, components/templates/HomePage/styles.js, components/templates/NewsPage/NewsHero.js, components/templates/NewsPage/index.js, components/templates/NewsPage/styles.js, components/templates/Page/index.js, lib/api/fragments/educator-page.js, lib/api/fragments/event.js, lib/api/fragments/homepage.js, lib/api/fragments/news-post.js, lib/api/fragments/page.js, lib/api/fragments/student-page.js
- More drop shadow on Hero text
- Heading is optional for GridBlock (CTAGrid)
- Hero image positionable via focalPoint values
- StepNavigation mobile and desktop layouts more closely approximate original design
- Breadcrumb wraps and never overflows
- Breadcrumb hidden on screens >= 600px wide (wider than previously)
- New center aligned layout for Callouts without images
=> Homepage tweaks

components/global/Header/NavItemWithChildren.js, components/global/Header/Navigation.js, components/global/Header/Subnavigation.js, components/global/Header/_header.scss, components/global/Header/_navigation.scss, components/global/Header/_subnavigation.scss, components/global/Header/_subsubnavigation.scss, components/global/Header/index.js, lib/api/fragments/global.js, lib/api/global.js, theme/styles/abstracts/_variables.scss, theme/styles/components/_index.scss, theme/styles/globalStyles.js
Must test with https://github.com/lsst-epo/rubin-obs-api/pull/224
Introduces a sense of a 3rd level to the Header Nav.  Design is not quite consistent with Jose's original vision as implementing a non-accordion 3rd level in the desktop nav proved to be much more involved than anticipated.  Could circle back on that in the future, but was eager to release this work as-is so that Kristen and Steph may begin reorganizing the pagetree ASAP.  In addition to new styles and functionality to support a 3rd level, there are also many small stylistic updates to the header and the nav in general (all as seen in Jose's latest design).
On Desktop:
- If a nav drop down is open it should remain open, and the header should remain visible on scroll
On mobile:
- If a mobile nav is open it should remain …
=> 3 level desktop nav

components/global/Header/Navigation.js, components/page/Breadcrumbs/index.js, components/page/Breadcrumbs/styles.js, components/templates/EventPage/index.js, components/templates/GalleryPage/index.js, components/templates/GlossaryPage/index.js, components/templates/NewsPage/index.js, components/templates/Page/index.js, components/templates/SearchPage/index.js, components/templates/SlideshowPage/index.js, components/templates/StaffPage/index.js, package.json, yarn.lock
Resolves #459 
Update React to 18.3 to prepare for React 19. Upgrade includes:
- Remove deprecated `defaultProps` from `Navigation` and replace with destructuring defaults
- Upgrade `@castiron/components-breadcrumbs` to remove incorrect dependency on `react-dom@17`
- Remove `active: true` from breadcrumbs that prompts an invalid attribute error
- Replace legacy `Link` setup on breadcrumb links.
=> [C] update React

components/page/FilterBar/index.js, components/page/FilterBar/styles.js, components/templates/Page/index.js, contexts/FilterParams.js, cypress/e2e/filtering.cy.js, lib/api/fragments/page.js, lib/utils.js
Events pages (like `/calendar`) can be pre-filtered by the server to only show specific event types like Science, Education, Press, etc. When a page is pre-filtered by the server, the "Filter" dropdown will not be available and the filters will not show up in the URL parameters.
To accomplish this, control of the URL parameters is removed from `FilterBar` and put into a context that wraps the `FilterBar` and then the display components that use the URL parameters to make GraphQL requests. This context accepts the server filters applied, and merges them with any client-side filters then provides that via a hook.
If the provider is not supplied, the hook will return the URL parameters from the router. 
Additionally an E2E test is supplied that validates the function of the filter/sort …
=> [F] events pages can be filtered by server

components/page/Hero/styles.js, components/templates/NewsPage/styles.js
Add `!important` to hero image height so that even if styled-components renders classes out of order, images will not overflow their hero container and will preserve the `object-fit` and `object-position` attributes.
=> [C] set height important on hero images

components/page/FilterBar/index.js, components/templates/SearchPage/index.js, cypress/e2e/filtering.cy.js, cypress/e2e/search.cy.js
The `FilterBar` for the search page was not wrapped in it's provider and did not have access to the `resetParams` and `setParams` methods. 
Wrapped in the search page and added e2e test for the search page 
Resolves #496
=> bug: clear/change search not working

components/content-blocks/Callout/CalloutEntry/index.js, components/content-blocks/GridBlock/CarouselGrid/index.js, components/content-blocks/GridBlock/NewsGrid.js, components/dynamic/EventList/index.js, components/dynamic/NewsList/index.js, components/dynamic/RelatedList/index.js, components/global/Body/index.js, components/global/HtmlHead/index.js, components/templates/EventPage/index.js, components/templates/GalleryPage/index.js, components/templates/GlossaryPage/index.js, components/templates/NewsPage/index.js, components/templates/Page/index.js, components/templates/SlideshowPage/index.js, components/templates/StaffPage/index.js, lib/api/fragments/content-blocks.js, lib/api/fragments/educator-page.js, lib/api/fragments/event.js, lib/api/fragments/news-post.js, lib/api/fragments/page.js, lib/api/fragments/staff-profile.js, lib/api/fragments/student-page.js, lib/api/gallery-items.js, lib/api/noirlabReleases.js, lib/api/slideshows.js, lib/utils.js
Remove the `featuredImage` query everywhere except for Investigation landing pages (which have no other image to show in search/opengraph) and replace with a cropped version of the hero image or first NoirLab press release image.
Resolves #500
=> refactor: use hero for all opengraph and search images

components/atomic/Button/patterns/GoogleSSOButton.js, components/auth/AuthorizePage/index.js, components/dynamic/DataList/index.js, components/global/Header/SearchBar.js, components/layout/NavButtons/index.js, components/modal/ActivateModal/index.js, components/modal/ForgotPasswordModal/index.js, components/modal/RegisterModal/index.js, components/modal/SSOModal/index.js, components/modal/SetPasswordModal/index.js, components/modal/SignInModal/index.js, components/page/FilterBar/index.js, components/page/Pagination/index.js, components/templates/Page/index.js, components/templates/SearchPage/index.js, contexts/FilterParams.js, hooks/useAuthModal.js, hooks/useAuthentication.js, lib/routing/useQueryParams.js, lib/utils.js
Replaces instances of `next/router` with the app directory compatible `next/navigation`. Replacements include:
- `router.query` replaced with `useQueryParams` hook that composes `useSearchParams` and `usePathname`
- `router.pathname` replaced with `usePathname`
- `router.asPath` replaced with combining `usePathname` and `useQueryParams`
- `usePathData` and `normalizePathData` deprecated and removed in favor of `usePathname` and `useQueryParams`
Resolves #513 
- open modals with query params:
- ?signIn=true - sign in
- ?activate=true - activate account (requires code and id param also, will show error otherwise)
- ?forgotPassword=true - forgot password
- ?register=true - registration start
- ?set_password=true - set password
- ?sso=true - Google signin (will just be a blank modal)
- can …
=> refactor: replace next/router with next/navigation

lib/api/entries.js, lib/api/global.js, lib/utils.js, pages/[locale]/[...uriSegments]/index.js, pages/[locale]/index.js, pages/api/preview.js
Separate the homepage from the `[...uriSegments]` catch-all since it has unique queries and URI structures. 
Side effect, refactor `getGlobalData` to query by current site rather than querying all sites and then filtering.
Optimization benefits of separation:
- 100kb rendered, 381kb first load JS (per-page)
- 1.4mb total transferred
- 480kb JS
- 2.75kb rendered, 352kb first load JS (for homepage)
- 1.3mb total transferred
- 397kb JS
Resolves #495
=> refactor: separate homepage from urisegments

app/api/app-revalidate/route.ts, next-env.d.ts, pages/api/revalidate.js, tsconfig.json
Adds an app directory Route Handler that performs revalidation to support to our existing `revalidate` endpoint. The existing `api/revalidate` endpoint will call this new `api/app-revalidate` endpoint with the same arguments.
Testing this is tricky, since we do not have any app directory routes, but can be done with the following:
- add an `app` folder with `[locale]` as a child folder, and `my-page` as a folder within `[locale]`. 
```
app
|- [locale]
|- my-page
|- page.jsx
```
- add a `page.jsx` to `my-page` that default exports a React component. Inside the component, fetch a random number from an API and display it.
- 
```jsx
const Page = async () => {
const response = await fetch('http://www.randomnumberapi.com/api/v1.0/random?min=100&max=1000&count=1');
const number = await …
```
=> refactor: add revalidatePath support to revalidate endpoint

pages/api/preview.js
`setPreviewData` needs to be in front of `redirect` or it will never be reached
=> fix: re-order preview data set

app/[locale]/layout.tsx
Since we use dynamic page generation, we can't rely on `generateStaticParams` to exclude non-matching segments like the `locale`. These must be manually excluded and redirected to 404's.
=> fix: reject non-matching locales

app/[locale]/sitemap.xml/route.ts, app/sitemap_index.xml/route.ts, cypress/e2e/api/sitemaps.cy.js, lib/api/homepage/index.ts, lib/api/sitemap/index.ts, lib/constants/index.ts, package.json, yarn.lock
Resolves #563 
Adds a sitemap index and a sitemap for each locale. Unfortunately the built-in sitemap API in Next.js does not support a [sitemap index](https://developers.google.com/search/docs/crawling-indexing/sitemaps/large-sitemaps), or extending the sitemap for [News](https://developers.google.com/search/docs/crawling-indexing/sitemaps/news-sitemap) or [Image](https://developers.google.com/search/docs/crawling-indexing/sitemaps/image-sitemaps) formats.
Given these limitations, the sitemaps are instead generated with two route handlers and an XML parsing library. 
Includes Cypress test that validates the sitemap endpoints are generating valid XML
=> feat: sitemaps

lib/api/sitemap/index.ts
Bing couldn't parse URL's where the slashes were encoded, so instead just encode the segments and then re-combine.
=> fix: do not encode URI slashes

app/[locale]/[...uriSegments]/page.tsx, app/[locale]/page.tsx
Resolves #590 
Adds a `canonical` tag to each page so that search engines do not attempt to index query params
=> fix: add canonical to document meta

app/[locale]/[...uriSegments]/page.tsx, app/[locale]/layout.tsx, app/[locale]/page.tsx, lib/api/noirlab/index.ts
Resolves #596, #564 
- moves canonical up to root level
- adds Twitter handle
- adds large preview image for Google
=> feat: twitter + google meta tags

app/[locale]/[...uriSegments]/page.tsx, app/[locale]/gallery/[gallery]/[image]/page.tsx, app/[locale]/gallery/[gallery]/page.tsx, app/[locale]/gallery/page.tsx, app/[locale]/page.tsx, types/next.d.ts
Resolves #602 
Set up route structure for gallery pages. This work has been put into it's own feature branch off of develop, because the `/gallery` route segment will override the existing segment due to matching priority.
=> feat: gallery route structure

lib/i18n/client.js, lib/i18n/server.ts, middleware.js, package.json, yarn.lock
Resolves #587 
- replaced `next-intl/middleware` with the smaller `next-i18n-router` since we no longer need hybrid pages/app support
- set i18next to use the same locale determination order as Investigations, with the HTML `lang` attribute at highest priority
=> refactor: i18n cleanup

components/atomic/StructuredData/StructuredData.cy.tsx, components/atomic/StructuredData/index.tsx, package.json, tsconfig.json, yarn.lock
Resolves #583 
Adds a structured data component to enable future SEO work, includes Cypress test for rendering and that schema context is attached. Full schema validation testing is overkill, the component is strongly typed and would require installing validator packages that would otherwise be unused.
=> feat: StructuredData component

app/[locale]/layout.tsx, app/not-found.tsx, theme/styles/globalStyles.js, theme/styles/mixins/appearance.js
In preparation for changes to the header, update the rubin-obs-client to use the global styles defined by the epo-react-lib so we can make use of the most up-to-date Rubin style tokens. 
The epo-react-lib global styles are based on rubin-obs-client's styles, so there should be no visual impact from this change. 
Resolves #617
=> refactor: use library global styles

components/templates/NewsPage/index.tsx, lib/utils.js
Resolves #621 
First verify issue seen in #621, then retry with same timezones on this branch.
=> fix: put timezone offset into date

components/atomic/Loader/index.js, components/atomic/Loader/styles.js, components/atomic/Loader/styles.module.css, package.json, postcss.config.js, tsconfig.json, yarn.lock
Set up rubin-obs-client to use CSS modules so that future features can use CSS instead of runtime `styled-components`.
- fixed duplicate postcss reset imports
- fixed stylelint unknown error in CSS files
- added CSS files to stylelint
- added CSS modules typing
- added CSS modules demo in `Loader`
=> build(styles): add CSS modules support

components/molecules/TagList/TagList.cy.js, components/molecules/TagList/index.tsx, components/molecules/TagList/styles.module.css, components/page/Aside/Tags/index.js, components/page/Aside/Tags/styles.js
Molecule for tag lists that will be used in news asides, staff profile asides, and gallery image details
Replaces existing molecule for news articles and staff profiles, adds unit test
=> feat: TagList molecule

app/api/canto/[scheme]/[id]/[directUrlOriginalHash]/route.ts
Prohibit downloads that are not from the same origin, add "noindex" headers to image responses.
=> fix: csrf + noindex for gallery downloads

app/[locale]/[...uriSegments]/layout.tsx, app/[locale]/[...uriSegments]/page.tsx, app/[locale]/layout.tsx, app/[locale]/page.tsx, app/[locale]/search/page.tsx, app/api/preview/route.ts, codegen.ts, components/organisms/PreviewMode/Banner/index.tsx, components/organisms/PreviewMode/Banner/styles.module.css, components/organisms/PreviewMode/index.tsx, components/templates/SlideshowPage/index.tsx, gql/gql.ts, lib/api/client/query.ts, lib/api/entries.js, lib/api/entries/index.ts, lib/api/entry/index.ts, lib/api/fragments/galleries.ts, lib/api/galleries/index.ts, lib/api/homepage/index.ts, lib/api/metadata/index.ts, lib/api/search/index.ts, lib/api/slideshows/index.ts, lib/i18n/localeStrings/en/translation.json, package.json, services/actions/endPreviewMode.ts, services/sessions/preview.ts, tsconfig.json, yarn.lock
Resolves #708 
Instead of manually affixing the Craft preview token to the search params, the token is committed to a session cookie which is automatically appended by the GraphQL client on queries. 
Since both Next draftMode and the preview token cookies are session cookies, they are not cleared until the browser is closed. To avoid getting stuck in preview mode, a banner is shown indicating preview mode with a button to disable it.
Testing
- Check out a live preview in Craft like a page, gallery, or news article
- Check out the non-live preview ("View") and see that the preview mode banner appears
- Click "disable" on the preview mode banner and see that any draft changes disappear
Does the language on the banner make sense? Would "Exit" be a better CTA on the button?
=> refactor: preview token into session

middleware.js
fix: remove `localhost` cond in middleware logging
=> fix: remove `localhost` cond in middleware logging

components/organisms/gallery/CantoImage/index.tsx, lib/api/canto/resize.ts
Resolves #761 
Uses the 2050px version of the Canto preview instead of the full resolution so ultra-large images do not gum up the Next image optimizer
=> fix: use smaller Canto preview

components/content-blocks/Callout/Wrapper.js, components/content-blocks/Callout/styles.js
The callouts contain a re-implementation of the [Container](https://github.com/lsst-epo/epo-react-lib/blob/main/packages/epo-react-lib/src/molecules/Container/index.tsx) component in the `@rubin-epo/epo-react-lib`. The `Container` was updated months ago to interpret the `bgColor` prop as a CSS variable.
The reimplementation was not updated, and used a static map of background colors. When the background color returned undefined from the map, and was passed to the `needsDarkerColor` method, an exception was thrown. 
Updating to CSS variables removes this exception path, and if no matching CSS variable is found then the property is invalid and ignored.
=> fix: remove hardcoded color map from callouts

helpers/noirlab.cy.ts, helpers/noirlab.ts, lib/i18n/index.ts
Some image and video links coming from NOIRLab are prefixed with their locale (en or es). When I initially set up the URL re-writes, the links tested did not fall under this category and so I extracted from the URL starting from the beginning. With these locale prefixes set, values were off by 1 index.
Change to pull from the end of the URL instead since the only two values we need are at the end: asset ID and category.
Add tests around some of the low level helpers including the URL re-writer
Testing:
- Observe the initial issue here: https://rubinobservatory.org/news/host-first-look-watch-party
- Spanish link is: https://rubinobservatory.org/gallery/collections/news-es/images when it should be https://rubinobservatory.org/gallery/collections/news-images/ann25007a
- Check locally by …
=> fix: parse localized image links

components/organisms/Header/LanguageSelect/index.js, cypress/e2e/header.cy.js, cypress/e2e/i18n.cy.ts, env.ts, lib/i18n/client.js, lib/i18n/index.ts, lib/i18n/options.ts, lib/i18n/settings.ts
Resolves #829 
The client router needs to be refreshed after locale changes, or else after switching from Spanish -> English, next will still include the pathname prefixed with `es` which triggers the i18n to perform a manual switch to Spanish and reset the cookie.
=> fix: clear client cache after changing locale

app/[locale]/gallery/collections/[gallery]/[asset]/page.tsx, components/molecules/SharePopup/index.tsx
Resolves #777 
Adds image files on the gallery pages to the web share setup. Does not apply to:
- Video pages, because downloading a video to put into the share files would take too long
- NOIRLab pages, because the share API rejects files from a cross origin domain
=> feat: web share for image files

app/[locale]/layout.tsx, app/api/revalidate/route.ts, components/organisms/PreviewMode/Banner/index.tsx, components/organisms/PreviewMode/Banner/styles.module.css, components/organisms/PreviewMode/Disable/index.tsx, components/organisms/PreviewMode/Revalidate/index.tsx, components/organisms/PreviewMode/Revalidate/styles.module.css, components/organisms/PreviewMode/index.tsx, components/organisms/PreviewMode/styles.module.css, lib/i18n/localeStrings/en/translation.json, services/actions/revalidate.ts, services/revalidation/additional.ts, services/revalidation/index.ts
Resolves #862 
Adds revalidation requests to the preview pane, with tooltip explaining the purpose of the feature.
To test:
- Open up a page in preview mode
- Back in Craft, make a change _but do not save_, since we're in preview mode we can get the draft data from Craft without saving
- In the preview page, click "Revalidate", and receive a success message
- See the page update with your change
=> feat: revalidation from preview mode

app/[locale]/gallery/collections/[gallery]/[asset]/layout.tsx, app/[locale]/gallery/collections/[gallery]/[asset]/page.tsx, app/[locale]/gallery/collections/[gallery]/layout.tsx, app/[locale]/gallery/collections/[gallery]/page.tsx, lib/api/galleries/asset.ts
Resolves #853
Turns on static generation for Canto gallery pages, will generate the first page of gallery assets for each gallery during build
=> refactor: statically render canto gallery pages

components/molecules/Pagination/index.tsx, components/molecules/Pagination/styles.module.css, components/molecules/TagList/index.tsx, components/organisms/Header/Subnavigation.js
Disables prefetch on the navigation menus. Prefetch is ok for the mobile menu, where it's not initiated til the menu slides open, but on desktop the menu is considered always in viewport and all top level items are prefetched.
=> fix: disable prefetch on navigation menu

app/[locale]/gallery/collections/[gallery]/[asset]/page.tsx
fix: fixed copy-url in gallery asset details page
=> fix: fixed copy-url in gallery asset details page
